<a href="https://colab.research.google.com/github/Prathyusha-Pasupuleti/Internship/blob/main/Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
datasetPath ='/content/drive/MyDrive/retail_transactions.csv'

In [ ]:
df = pd.read_csv(datasetPath)

In [ ]:
df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,NaN
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0
...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0

In [ ]:
#1.Data loading and phrasing

In [ ]:
from datetime import datetime

In [ ]:
df['TransactionDate']=pd.to_datetime(df['TransactionDate'])

In [ ]:
#2 .Initial Data Exploration

In [ ]:
#Displsy first 15 rows in DataFrame

df.head(15)

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount,NetPrice,TotalSale
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0,127.50,127.5
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0,285.30,570.6
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,0.0,165.00,825.0
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0,446.40,2678.4
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0,166.00,1660.0
5,T006,2024-01-06,103,1836,515,Grocery,9,227,Debit,0.0,227.00,2043.0
6,T007,2024-01-07,103,1983,586,Electronics,1,170,Credit,0.0,170.00,170.0
7,T008,2024-01-08,101,1806,569,Toys,4,500,Debit,0.0,500.00,2000.0
8,T009,2024-01-09,101,1925,548,Apparel,7,217,Cash,10.0,195.30,1367.1
9,T010,2024-01-10,101,1711,565,Furniture,3,466,Debit,5.0,442.70,1328.1
10,T011,2024-01-11,103,1276,565,Furniture,1,321,Cash,0.0,321.00,321.0
11,T012,2024-01-12,101,1486,523,Toys,8,426,Credit,5.0,404.70,3237.6
12,T013,2024-01-13,103,1597,516,Toys,5,262,Cash,15.0,222.70,1113.5
13,T014,2024-01-14,101,1462,520,Electronics,10,218,Cash,0.0,218.00,2180.0
14,T015,2024-01-15,104,1668,581,Toys,4,201,Debit,15.0,170.85,683.4

In [ ]:
#print summary info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    100 non-null    object
 1   TransactionDate  100 non-null    datetime64[ns]
 2   StoreID          100 non-null    int64
 3   CustomerID       100 non-null    int64
 4   ProductID        100 non-null    int64
 5   ProductCategory  100 non-null    object
 6   Quantity         100 non-null    int64
 7   Price            100 non-null    int64
 8   PaymentType      100 non-null    object
 9   Discount         100 non-null    float64
 10  NetPrice         100 non-null    float64
 11  TotalSale        100 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(5), object(3)
memory usage: 9.5+ KB

In [ ]:
#print summary describe()
df.describe()

,TransactionDate,StoreID,CustomerID,ProductID,Quantity,Price,Discount,NetPrice,TotalSale
count,100,100.000000,100.000000,100.000000,100.000000,100.00000,100.00000,100.000000,100.000000
mean,2024-02-19 12:00:00,102.730000,1552.520000,554.390000,5.370000,282.15000,5.80000,266.211000,1456.037000
min,2024-01-01 00:00:00,101.000000,1013.000000,501.000000,1.000000,50.00000,0.00000,50.000000,80.100000
25%,2024-01-25 18:00:00,101.000000,1310.250000,529.750000,3.000000,165.75000,0.00000,160.375000,453.150000
50%,2024-02-19 12:00:00,103.000000,1534.000000,554.000000,5.500000,280.00000,5.00000,251.750000,1133.700000
75%,2024-03-15 06:00:00,104.000000,1800.750000,579.500000,8.000000,415.25000,10.00000,390.250000,2157.375000
max,2024-04-09 00:00:00,105.000000,1983.000000,600.000000,10.000000,500.00000,15.00000,500.000000,4880.000000
std,NaN,1.384291,268.295461,28.544098,3.013957,140.19938,5.93398,135.318421,1188.135063

In [ ]:
#3. Data Cleaning

In [ ]:
#Check for missing values
df.isnull().sum()

TransactionID      0
TransactionDate    0
StoreID            0
CustomerID         0
ProductID          0
ProductCategory    0
Quantity           0
Price              0
PaymentType        0
Discount           0
NetPrice           0
TotalSale          0
dtype: int64

In [ ]:
#print count per column
df.count()

TransactionID      100
TransactionDate    100
StoreID            100
CustomerID         100
ProductID          100
ProductCategory    100
Quantity           100
Price              100
PaymentType        100
Discount           100
NetPrice           100
TotalSale          100
dtype: int64

In [ ]:
#for the columns Quality,Price and Discount ensure they are in numeric format

In [ ]:
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
df['Discount'] = pd.to_numeric(df['Discount'], errors='coerce')

In [ ]:
df['Discount'] = df['Discount'].fillna(0)

In [ ]:
df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount,NetPrice,TotalSale
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0,127.50,127.50
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0,285.30,570.60
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,0.0,165.00,825.00
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0,446.40,2678.40
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0,166.00,1660.00
...,...,...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0,395.10,790.20
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0,52.00,208.00
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0,135.90,951.30
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0,431.10,2155.50
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0,209.95,1049.75

In [ ]:
df['NetPrice'] = df['Price'] * (1 - df['Discount'] / 100)

In [ ]:
df['NetPrice']

0     127.50
1     285.30
2     165.00
3     446.40
4     166.00
       ...
95    395.10
96     52.00
97    135.90
98    431.10
99    209.95
Name: NetPrice, Length: 100, dtype: float64

In [ ]:
df['TotalSale'] = df['Quantity'] * df['NetPrice']

In [ ]:
df['TotalSale']

0      127.50
1      570.60
2      825.00
3     2678.40
4     1660.00
       ...
95     790.20
96     208.00
97     951.30
98    2155.50
99    1049.75
Name: TotalSale, Length: 100, dtype: float64

In [ ]:
filtered_df = df[df['TotalSale'] >= 20]

In [ ]:
filtered_df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount,NetPrice,TotalSale
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0,127.50,127.50
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0,285.30,570.60
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,0.0,165.00,825.00
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0,446.40,2678.40
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0,166.00,1660.00
...,...,...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0,395.10,790.20
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0,52.00,208.00
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0,135.90,951.30
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0,431.10,2155.50
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0,209.95,1049.75

In [ ]:
df1 = filtered_df

In [ ]:
df1

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount,NetPrice,TotalSale
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0,127.50,127.50
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0,285.30,570.60
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,0.0,165.00,825.00
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0,446.40,2678.40
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0,166.00,1660.00
...,...,...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0,395.10,790.20
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0,52.00,208.00
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0,135.90,951.30
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0,431.10,2155.50
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0,209.95,1049.75

In [ ]:
filtered_df['PaymentType'] = filtered_df['PaymentType'].astype('category')

In [ ]:
filtered_df['PaymentType']

0     Credit
1      Debit
2      Debit
3      Debit
4      Debit
       ...
95      Cash
96     Debit
97    Credit
98    Credit
99    Credit
Name: PaymentType, Length: 100, dtype: category
Categories (3, object): ['Cash', 'Credit', 'Debit']

In [ ]:
category_sales = filtered_df.groupby('ProductCategory').agg(
    TotalQuantity=('Quantity', 'sum'),
    TotalSales=('TotalSale', 'sum')
)

In [ ]:
category_sales = category_sales.sort_values(by='TotalSales', ascending=False)

In [ ]:
category_sales

                 TotalQuantity  TotalSales
ProductCategory
Toys                       137    44326.35
Furniture                  130    39655.55
Apparel                    117    28055.35
Grocery                     75    17585.80
Electronics                 78    15980.65

In [ ]:
top_3_categories = category_sales.head(3)

In [ ]:
top_3_categories

                 TotalQuantity  TotalSales
ProductCategory
Toys                       137    44326.35
Furniture                  130    39655.55
Apparel                    117    28055.35

In [ ]:
%matplotlib inline

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
store_category_sales

    StoreID ProductCategory    TotalSale
0       101         Apparel  1344.550000
1       101     Electronics  1128.916667
2       101       Furniture  1317.943750
3       101            Toys  2227.016667
4       102         Apparel  1452.180000
5       102     Electronics   591.380000
6       102       Furniture  2565.900000
7       102         Grocery   171.900000
8       102            Toys  1036.557143
9       103         Apparel  1021.950000
10      103     Electronics   817.666667
11      103       Furniture  1560.771429
12      103         Grocery   954.850000
13      103            Toys  1239.180000
14      104         Apparel   722.000000
15      104     Electronics   852.333333
16      104       Furniture  1528.928571
17      104         Grocery  1118.833333
18      104            Toys  1367.700000
19      105         Apparel  2398.450000
20      105     Electronics  2313.500000
21      105       Furniture  1176.150000
22      105         Grocery  2047.600000
23      105            Toys  4048.000000

In [ ]:
top_category_per_store = store_category_sales.loc[store_category_sales.groupby('StoreID')['TotalSale'].idxmax()]

In [ ]:
top_category_per_store

    StoreID ProductCategory    TotalSale
3       101            Toys  2227.016667
6       102       Furniture  2565.900000
11      103       Furniture  1560.771429
16      104       Furniture  1528.928571
23      105            Toys  4048.000000